spring.application.name=api_student_management

server.port = 8080

#PostgreSQL 1
app.datasource.primary.url=jdbc:postgresql://localhost:5432/student_management
app.datasource.primary.username=${DB_USERNAME:student_admin}
app.datasource.primary.password=${DB_PASSWORD:Student!@#123} 
app.datasource.primary.driver-class-name=org.postgresql.Driver


#PostgreSQL 2 
app.datasource.secondary.url=jdbc:postgresql://localhost:5432/audit_management
app.datasource.secondary.username=${DB_USERNAME:student_admin}
app.datasource.secondary.password=${DB_PASSWORD:Student!@#123}
app.datasource.secondary.driver-class-name=org.postgresql.Driver

# JPA and HIBERNATE
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false 

# Display useful and error during development 
server.error.include-message=always 
server.error.include-binding-errors=always

# JWT 
jwt.secret = ${JWT_SECRET:student-api-development-secret-key-123456789}
jwt.expiration=3600
jwt.issuer= student-management-api

# Third Party
third-party.providers.json-placeholder.base-url=https://jsonplaceholder.typicode.com
third-party.providers.json-placeholder.timeouts=0s

third-party.providers.second-api.base-url=https://api.example.com
third-party.providers.second-api.timeouts=5s

# Redis Cache
spring.data.redis.host = localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.password=
spring.cache.type = redis 
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false

atomikos.properties.transaction-manager-unique-name=student-api-local-01
atomikos.properties.log-base-dir=./transaction-logs
atomikos.properties.enable-logging=true
atomikos.properties.default-jta-timeout=30s
atomikos.properties.max-timeout=60s
